### ISSUE TITLE
"Invalid argument (os error 22)" when trying to normalize paths

### ISSUE THREAD

**Issue by Calistex** [mq1/TinyWiiBackupManager#444]
I get an "Invalid argument (os error 22)" popup when trying to normalize paths. 
Program version is 4.9.6, Linux x86_64 v3, I'm on Linux Mint, the drive is an external hard disk NTFS formatted.

**Comment by mq1** [comment]
I just merged #445 and released v4.9.7

Does this issue persist?

**Comment by Calistex** [comment]
Yes, same error

**Comment by mq1** [comment]
> Yes, same error

Are you able to provide your drive layout? like with `ls -R` or `find .` in your drive root

**Comment by Calistex** [comment]
Unfortunately it's a 1 tb drive I use for pretty much everything and it's full of stuff, but in the drive root there is the `wbfs` folder with the following content, if it can be of any help:
```
.:
'Animal Crossing Wii [RUUP01]'          'Kirby Wii [SUKP01]'                'New SUPER MARIO BROS. Wii [SMNP01]'  'The Legend of Zelda Skyward Sword [SOUP01]'
 disc.info                              'LINKS CROSSBOW TRAINING [RZPP01]'  'Punch Out [R7PE01]'                  'The Legend of Zelda - Skyward Sword-temp'
'Donkey Kong Country Returns [SF8E01]'  'MarioKartWii [RMCP01]'             'SUPER MARIO GALAXY [RMGE01]'         'The Legend of Zelda Twilight Princess [RZDP01]'
'Just Dance 2014 [SJOP41]'              'Monster Hunter Tri [RMHP08]'       'SUPER PAPER MARIO [R8PP01]'          'Wii Sports + Wii Sports Resort [SP2P01]'
'Kirby'\''s Epic Yarn [RK5P01]'         'MySims SkyHeroes [RJ6P69]'         'Super Smash Bros. Brawl [RSBP01]'

'./Animal Crossing Wii [RUUP01]':
RUUP01.wbfs

'./Donkey Kong Country Returns [SF8E01]':
SF8E01.wbfs

'./Just Dance 2014 [SJOP41]':
SJOP41.wbf1  SJOP41.wbfs

'./Kirby'\''s Epic Yarn [RK5P01]':
RK5P01.wbfs

'./Kirby Wii [SUKP01]':
SUKP01.wbfs

'./LINKS CROSSBOW TRAINING [RZPP01]':
RZPP01.wbfs

'./MarioKartWii [RMCP01]':
RMCP01.wbfs

'./Monster Hunter Tri [RMHP08]':
RMHP08.wbfs

'./MySims SkyHeroes [RJ6P69]':
RJ6P69.wbfs

'./New SUPER MARIO BROS. Wii [SMNP01]':
SMNP01.wbfs

'./Punch Out [R7PE01]':
R7PE01.wbfs

'./SUPER MARIO GALAXY [RMGE01]':
RMGE01.wbfs

'./SUPER PAPER MARIO [R8PP01]':
R8PP01.wbfs

'./Super Smash Bros. Brawl [RSBP01]':
RSBP01.wbfs

'./The Legend of Zelda Skyward Sword [SOUP01]':
SOUP01.iso

'./The Legend of Zelda - Skyward Sword-temp':
gc.dat  SOUP01.bca  SOUP01.part0.iso  wii.dat

'./The Legend of Zelda Twilight Princess [RZDP01]':
RZDP01.wbfs

'./Wii Sports + Wii Sports Resort [SP2P01]':
SP2P01.wbfs

```

**Comment by mq1** [comment]
I think the issue could be the ' characters. I released v4.9.8 with more aggressive string sanitization, if this doesn't work, could you try manually removing ' and \\' characters in the directory names?

**Comment by Calistex** [comment]
The error still persists, but now the ' and \ characters have been removed automatically. Here's the results of `ls -R`:
```
.:
'Animal Crossing Wii [RUUP01]'
 disc.info
'Donkey Kong Country Returns [SF8E01]'
'Just Dance 2014 [SJOP41]'
'Kirbys Epic Yarn [RK5P01]'
'Kirby Wii [SUKP01]'
'LINKS CROSSBOW TRAINING [RZPP01]'
'MarioKartWii [RMCP01]'
'Monster Hunter Tri [RMHP08]'
'MySims SkyHeroes [RJ6P69]'
'New SUPER MARIO BROS Wii [SMNP01]'
'Punch Out [R7PE01]'
'SUPER MARIO GALAXY [RMGE01]'
'SUPER PAPER MARIO [R8PP01]'
'Super Smash Bros Brawl [RSBP01]'
'The Legend of Zelda Skyward Sword [SOUP01]'
'The Legend of Zelda - Skyward Sword-temp'
'The Legend of Zelda Twilight Princess [RZDP01]'
'Wii Sports  Wii Sports Resort [SP2P01]'

'./Animal Crossing Wii [RUUP01]':
RUUP01.wbfs

'./Donkey Kong Country Returns [SF8E01]':
SF8E01.wbfs

'./Just Dance 2014 [SJOP41]':
SJOP41.wbf1  SJOP41.wbfs

'./Kirbys Epic Yarn [RK5P01]':
RK5P01.wbfs

'./Kirby Wii [SUKP01]':
SUKP01.wbfs

'./LINKS CROSSBOW TRAINING [RZPP01]':
RZPP01.wbfs

'./MarioKartWii [RMCP01]':
RMCP01.wbfs

'./Monster Hunter Tri [RMHP08]':
RMHP08.wbfs

'./MySims SkyHeroes [RJ6P69]':
RJ6P69.wbfs

'./New SUPER MARIO BROS Wii [SMNP01]':
SMNP01.wbfs

'./Punch Out [R7PE01]':
R7PE01.wbfs

'./SUPER MARIO GALAXY [RMGE01]':
RMGE01.wbfs

'./SUPER PAPER MARIO [R8PP01]':
R8PP01.wbfs

'./Super Smash Bros Brawl [RSBP01]':
RSBP01.wbfs

'./The Legend of Zelda Skyward Sword [SOUP01]':
SOUP01.iso

'./The Legend of Zelda - Skyward Sword-temp':
gc.dat  SOUP01.bca  SOUP01.part0.iso  wii.dat

'./The Legend of Zelda Twilight Princess [RZDP01]':
RZDP01.wbfs

'./Wii Sports  Wii Sports Resort [SP2P01]':
SP2P01.wbfs
```

On the other end, there was another error with a different code when I tried to remove the update partition from the games and now it says "No additional update partitions to remove were found", so I guess that's fixed.

**Comment by mq1** [comment]
I have now noticed the "The Legend of Zelda - Skyward Sword-temp" directory, I think this duplicate game could be the issue. does moving the -temp dir elsewhere (like in a ../wbfs-temp) prevent the error?

**Comment by Calistex** [comment]
Moved the directory elsewhere but the error still remains. If it can be of any help I could try to provide you any kind of log if you tell me how to do it, in case you don't have any more suggestions.

**Comment by mq1** [comment]
Is the "games" dir present in the root of the drive? are there any games in it?

**Comment by Calistex** [comment]
I think this is the problem. I have a games dir with two iso inside, I had added them without using Twbm and they were not inside a folder each. When trying to normalize the path, one of the two iso gets renamed into "game.iso" and then it gives the os error 22. Adding the games using the Add games feature creates the appropriate folders and when I try to normalize it doensn't give the error anymore.

**Comment by mq1** [comment]
Thank you for the feedback! Now v4.9.10 handles plain files in ./games and .wbfs

**Comment by Calistex** [comment]
I confirm the isos now get put in their own respective folders correctly. This is a great piece of software and it's the only available choice I've found for Linux, thank you for everything.

**Comment by mq1** [comment]
> I confirm the isos now get put in their own respective folders correctly. This is a great piece of software and it's the only available choice I've found for Linux, thank you for everything.

Thank you for the help sorting this out. Happy holidays!
